groups:
  - name: alertas-fase4
    rules:
      - alert: CPUAlta
        expr: rate(node_cpu_seconds_total{mode!="idle"}[1m]) > 0.8
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "CPU alta en {{ $labels.instance }}"

      - alert: SitioInalcanzable
        expr: probe_success == 0
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "El sitio está caído: {{ $labels.instance }}"

      - alert: ContenedorSinMemoria
        expr: container_memory_usage_bytes > 500000000
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Uso de memoria elevado en contenedor {{ $labels.name }}"


      - alert: LatenciaAlta
        expr: probe_duration_seconds > 2
        for: 30s
        labels:
          severity: warning
        annotations:
          summary: "Latencia alta en {{ $labels.instance }}"
          description: "El endpoint {{ $labels.instance }} está tardando más de 2 segundos en responder."


      - alert: MultiplesHostsCaidos
        expr: count(up == 0) > 2
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Múltiples hosts están caídos"
          description: "Más de 2 targets están sin respuesta. Verifica conectividad o estado de los servicios."
      
